[package]
name = "libloadorder-ffi"
version = "10.0.0"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]
build = "build.rs"

[dependencies]
libloadorder = { version = "10.0.0", path = ".." }
libc = "*"

[lib]
name = "loadorder_ffi"
crate-type = ["staticlib"]

[features]
default = []
ffi-headers = ["cbindgen"]

[build-dependencies]
cbindgen = { version = "0.1.23", optional = true }
