language = "C"
trailer = """
#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned int LIBLO_OK;
extern const unsigned int LIBLO_WARN_LO_MISMATCH;
extern const unsigned int LIBLO_ERROR_FILE_NOT_UTF8;
extern const unsigned int LIBLO_ERROR_FILE_NOT_FOUND;
extern const unsigned int LIBLO_ERROR_FILE_RENAME_FAIL;
extern const unsigned int LIBLO_ERROR_TIMESTAMP_WRITE_FAIL;
extern const unsigned int LIBLO_ERROR_FILE_PARSE_FAIL;
extern const unsigned int LIBLO_ERROR_INVALID_ARGS;
extern const unsigned int LIBLO_ERROR_POISONED_THREAD_LOCK;
extern const unsigned int LIBLO_ERROR_IO_ERROR;
extern const unsigned int LIBLO_ERROR_IO_PERMISSION_DENIED;
extern const unsigned int LIBLO_ERROR_TEXT_ENCODE_FAIL;
extern const unsigned int LIBLO_ERROR_TEXT_DECODE_FAIL;
extern const unsigned int LIBLO_ERROR_INTERNAL_LOGIC_ERROR;
extern const unsigned int LIBLO_RETURN_MAX;

extern const unsigned int LIBLO_METHOD_TIMESTAMP;
extern const unsigned int LIBLO_METHOD_TEXTFILE;
extern const unsigned int LIBLO_METHOD_ASTERISK;

extern const unsigned int LIBLO_GAME_TES3;
extern const unsigned int LIBLO_GAME_TES4;
extern const unsigned int LIBLO_GAME_TES5;
extern const unsigned int LIBLO_GAME_FO3;
extern const unsigned int LIBLO_GAME_FNV;
extern const unsigned int LIBLO_GAME_FO4;
extern const unsigned int LIBLO_GAME_TES5SE;

#ifdef __cplusplus
}
#endif
"""

[parse]
parse_deps = false
