sudo: false
language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - clang-3.8
      - libstdc++-5-dev
cache:
  directories:
    - $HOME/boost_1_61_0/boost
    - $HOME/boost_1_61_0/stage/lib

install:
  # Use the latest version of Clang/GCC.
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - chmod +x scripts/travis/install_boost.sh
  - scripts/travis/install_boost.sh

before_script:
  - mkdir build && cd build
  - cmake .. -DBOOST_ROOT=~/boost_1_61_0

script: make && ./tests
