[package]
name = "libloadorder"
version = "10.1.0"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]
description = "A free software library for manipulating the load order and active status of plugins for TES III: Morrowind, TES IV: Oblivion, TES V: Skyrim, Fallout 3, Fallout: New Vegas and Fallout 4."
documentation = "https://docs.rs/libloadorder"
repository = "https://github.com/WrinklyNinja/libloadorder.git"
readme = "README.md"
categories = ["games", "parsing"]
license = "GPL-3.0"
exclude = [
    "target/*",
]

[badges]
travis-ci = { repository = "WrinklyNinja/libloadorder" }
coveralls = { repository = "WrinklyNinja/libloadorder" }

[dependencies]
encoding = "0.2"
filetime = "0.1.10"
esplugin = "1.0.8"
regex = "0.2"
unicase = "2.0.0"
rayon = "0.9.0"

[target.'cfg(windows)'.dependencies]
app_dirs = "1.1.1"

[dev-dependencies]
criterion = "0.2.0"
tempdir = "0.3"

[lib]
name = "loadorder"

[workspace]
members = ["ffi"]

[[bench]]
name = "load_order"
harness = false
