[package]
name = "libloadorder"
version = "0.1.0"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]

[dependencies]
encoding = "0.2"
filetime = "0.1.10"
esplugin = "1.0.0"
regex = "0.2"
tempdir = "0.3"
unicase = "2.0.0"
walkdir = "1"

[target.'cfg(windows)'.dependencies]
app_dirs = "1.1.1"

[lib]
name = "loadorder"

[workspace]
members = ["ffi"]
