[package]
name = "libloadorder"
version = "10.0.3"
authors = ["Oliver Hamlet <oliver.hamlet@gmail.com>"]
description = "A free software library for manipulating the load order and active status of plugins for TES III: Morrowind, TES IV: Oblivion, TES V: Skyrim, Fallout 3, Fallout: New Vegas and Fallout 4."
documentation = "https://docs.rs/libloadorder"
repository = "https://github.com/WrinklyNinja/libloadorder.git"
readme = "README.md"
categories = ["games", "parsing"]
license = "GPL-3.0"
exclude = [
    "target/*",
]

[badges]
travis-ci = { repository = "WrinklyNinja/libloadorder" }
coveralls = { repository = "WrinklyNinja/libloadorder" }

[dependencies]
encoding = "0.2"
filetime = "0.1.10"
esplugin = "1.0.7"
regex = "0.2"
tempdir = "0.3"
unicase = "2.0.0"
walkdir = "1"
rayon = "0.8.2"

[target.'cfg(windows)'.dependencies]
app_dirs = "1.1.1"

[lib]
name = "loadorder"

[workspace]
members = ["ffi"]
